In [54]:
import numpy as np
import pandas as pd

In [82]:
train_df = pd.read_csv("data/customer_churn_dataset-training-master.csv")
train_df.shape

(440833, 12)

In [57]:
train_df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [58]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  str
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  str
 8   Contract Length    440832 non-null  str
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), str(3)
memory usage: 40.4 MB

In [59]:
train_df.duplicated().sum()

np.int64(0)

In [60]:
train_df.isnull().sum()

CustomerID           1
Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

In [83]:
train_df.dropna(inplace=True)

In [85]:
train_df.drop(columns = ['CustomerID'], inplace = True)

In [12]:
train_df['Subscription Type'].value_counts()

Subscription Type
Standard    149128
Premium     148678
Basic       143026
Name: count, dtype: int64

In [86]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(categories=[['Basic', 'Standard', 'Premium']])

train_df['Subscription Type'] = encoder.fit_transform(train_df[['Subscription Type']])
train_df = pd.get_dummies(data = train_df, columns = ['Contract Length', 'Gender'], drop_first = True, dtype=int)
train_df.head()

,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Total Spend,Last Interaction,Churn,Contract Length_Monthly,Contract Length_Quarterly,Gender_Male
0,30.0,39.0,14.0,5.0,18.0,1.0,932.0,17.0,1.0,0,0,0
1,65.0,49.0,1.0,10.0,8.0,0.0,557.0,6.0,1.0,1,0,0
2,55.0,14.0,4.0,6.0,18.0,0.0,185.0,3.0,1.0,0,1,0
3,58.0,38.0,21.0,7.0,7.0,1.0,396.0,29.0,1.0,1,0,1
4,23.0,32.0,20.0,5.0,8.0,0.0,617.0,20.0,1.0,1,0,1

In [87]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(train_df.drop(columns = ['Churn']), train_df['Churn'], test_size = 0.3, random_state = 0)

In [88]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns = scaler.get_feature_names_out())
X_val_scaled = pd.DataFrame(scaler.transform(X_val), columns = scaler.get_feature_names_out())

In [ ]:
import tensorflow as tf
from tensorflow import keras

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(3, activation='sigmoid', input_dim = 11))
model.add(Dense(1, activation='sigmoid'))

c:\Users\Keval\OneDrive\Desktop\Deep-Learning-Journey\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [70]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 3)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [90]:
model.compile(loss = 'binary_crossentropy', optimizer='Adam')

In [91]:
model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10
9644/9644 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - loss: 0.2675
Epoch 2/10
9644/9644 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - loss: 0.1792
Epoch 3/10
9644/9644 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - loss: 0.1459
Epoch 4/10
9644/9644 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - loss: 0.1324
Epoch 5/10
9644/9644 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - loss: 0.1270
Epoch 6/10
9644/9644 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - loss: 0.1242
Epoch 7/10
9644/9644 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - loss: 0.1225
Epoch 8/10
9644/9644 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step - loss: 0.1213
Epoch 9/10
9644/9644 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - loss: 0.1204
Epoch 10/10
9644/9644 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - loss: 0.1197

In [ ]:
model.layers[0].get_weights() # Weights and biases of the input layer

[array([[-0.08850044, -3.3951807 , -6.064884  ],
        [-0.04773825, -0.05488991,  0.08376588],
        [-0.04169117, -0.086686  ,  0.06205949],
        [-0.22769198,  8.312008  ,  0.20349416],
        [ 0.6146978 ,  0.59027857, -0.718108  ],
        [-0.01259315, -0.06047338,  0.08275158],
        [-5.878623  ,  0.20347032, -0.26242542],
        [ 0.32791597,  0.3766567 , -0.35499072],
        [ 4.683512  ,  3.8820474 , -6.05353   ],
        [-0.02095221, -0.01998293, -0.0215932 ],
        [-0.35494766, -0.36184976,  0.38882992]], dtype=float32),
 array([-2.4795523, -0.8683517,  3.3421586], dtype=float32)]

In [93]:
y_prob = model.predict(X_val_scaled)

threshold = 0.8

y_hat = np.where(y_prob > threshold, 1, 0)

4133/4133 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step

In [94]:
from sklearn.metrics import accuracy_score

accuracy_score(y_val, y_hat)

0.9573761814744801